services:
  # WordPress本体
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      # テーマとプラグインを同期
      - ./wp-content:/var/www/html/wp-content
      # 初期設定用SQLファイル（オプション）
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db

  # MySQL データベース
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      # データベースデータ（Gitには含めない）
      - db_data:/var/lib/mysql
      # 初期データ投入用SQLファイル
      - ./sql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

  # phpMyAdmin（データベース管理用）
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

  # WP-CLI（管理用）
  wp-cli:
    image: wordpress:cli
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./scripts:/scripts
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db
      - wordpress

volumes:
  db_data: